Repository cs2103-ay1819s2-w13-1/main, pull requests merged in 2019-04, with the labels that each got.

#109 add-appt storage fully working
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/AddAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/UniqueAppointmentList.java
  src/main/java/seedu/address/model/appointment/exceptions/AppointmentNotFoundException.java
  src/main/java/seedu/address/model/appointment/exceptions/DuplicateAppointmentException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/AddAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/AddDoctorCommandTest.java
  src/test/java/seedu/address/logic/commands/AddPatientCommandTest.java
  src/test/java/seedu/address/logic/parser/AddAppointmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/appointment/AppointmentTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/DoctorBuilder.java
Labels: priority.High

#115 fixing reposense
  .gitignore
  _reposense/config.json
  docs/UserGuide.adoc
Labels: type.Bug

#129 changed UI elements to follow abstraction principle
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ListAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/ListMedHistCommand.java
  src/main/java/seedu/address/logic/parser/AddAppointmentCommandParser.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
  src/main/java/seedu/address/ui/AppointmentCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DoctorListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PatientListPanel.fxml
  src/test/java/seedu/address/logic/commands/AddAppointmentCommandTest.java
  src/test/java/seedu/address/logic/parser/AddAppointmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DocXParserTest.java
  src/test/java/seedu/address/model/appointment/AppointmentTest.java
Labels: priority.High

#165 Initial OOP changes to doctor and patient
  src/main/java/seedu/address/logic/commands/EditDoctorCommand.java
  src/main/java/seedu/address/logic/commands/SearchDoctorSpecialisationCommand.java
  src/main/java/seedu/address/logic/parser/SearchDoctorSpecialisationCommandParser.java
  src/main/java/seedu/address/model/person/Doctor.java
  src/main/java/seedu/address/model/person/DoctorSpecialisationContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Patient.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/exceptions/DoctorNotFoundException.java
  src/main/java/seedu/address/model/person/exceptions/DuplicateDoctorException.java
  src/main/java/seedu/address/model/person/exceptions/DuplicatePatientException.java
  src/main/java/seedu/address/model/person/exceptions/DuplicatePersonException.java
  src/main/java/seedu/address/model/person/exceptions/PatientNotFoundException.java
  src/main/java/seedu/address/storage/JsonAdaptedDoctor.java
  src/main/java/seedu/address/storage/JsonAdaptedPatient.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/EditDoctorCommandParserTest.java
  src/test/java/seedu/address/model/person/UniqueDoctorListTest.java
  src/test/java/seedu/address/testutil/EditDoctorDescriptorBuilder.java
  src/test/java/seedu/address/ui/DoctorCardTest.java
  src/test/java/systemtests/DeleteDoctorCommandSystemTest.java
  src/test/java/systemtests/EditDoctorCommandSystemTest.java
Labels: priority.High

#173 add search-advanced command
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/SearchAdvancedPatientCommand.java
  src/main/java/seedu/address/logic/commands/SearchDoctorDidCommand.java
  src/main/java/seedu/address/logic/commands/SearchPatientPidCommand.java
  src/main/java/seedu/address/logic/commands/SearchPatientTagCommand.java
  src/main/java/seedu/address/logic/commands/SearchPatientWithApptStatusCommand.java
  src/main/java/seedu/address/logic/commands/SelectPatientCommand.java
  src/main/java/seedu/address/logic/parser/DocXParser.java
  src/main/java/seedu/address/logic/parser/SearchAdvancedPatientCommandParser.java
  src/main/java/seedu/address/logic/parser/SearchDoctorDidCommandParser.java
  src/main/java/seedu/address/logic/parser/SearchPatientCommandParser.java
  src/main/java/seedu/address/logic/parser/SearchPatientPidCommandParser.java
  src/main/java/seedu/address/logic/parser/SearchPatientTagCommandParser.java
  src/main/java/seedu/address/logic/parser/SearchPatientWithApptStatusCommandParser.java
  src/main/java/seedu/address/logic/parser/SelectCommandParser.java
  src/main/java/seedu/address/logic/parser/SelectPatientCommandParser.java
  src/main/java/seedu/address/model/person/AdvancedPatientSearchPredicate.java
  src/main/java/seedu/address/model/person/Gender.java
  src/main/java/seedu/address/model/person/Patient.java
  src/main/java/seedu/address/model/person/PatientApptStatusContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/storage/JsonAdaptedPersonIdCounter.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PatientCard.java
  src/main/java/seedu/address/ui/PatientInfoPanel.java
  src/main/resources/view/BrowserPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PatientInfoPanel.fxml
  src/main/resources/view/PatientListCard.fxml
  src/test/java/guitests/guihandles/BrowserPanelHandle.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/SelectPatientCommandTest.java
  src/test/java/seedu/address/logic/parser/DocXParserTest.java
  src/test/java/seedu/address/logic/parser/SelectPatientCommandParserTest.java
  src/test/java/seedu/address/ui/MainWindowCloseTest.java
  src/test/java/seedu/address/ui/PatientInfoPanelTest.java
  src/test/java/systemtests/DocXSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SelectDoctorCommandSystemTest.java
  src/test/java/systemtests/SelectPatientCommandSystemTest.java
Labels: type.Enhancement

#178 display of doctors' info in the browser panel
  src/main/java/seedu/address/commons/util/DoctorUtil.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DoctorMatchCommand.java
  src/main/java/seedu/address/logic/commands/SelectDoctorCommand.java
  src/main/java/seedu/address/logic/parser/DocXParser.java
  src/main/java/seedu/address/logic/parser/DoctorMatchCommandParser.java
  src/main/java/seedu/address/model/person/AppointmentContainsDoctorPredicate.java
  src/main/java/seedu/address/model/person/DoctorHasAppointmentPredicate.java
  src/main/java/seedu/address/model/person/DoctorMatch.java
  src/main/java/seedu/address/model/person/DoctorSpecialisationMatchesPredicate.java
  src/main/java/seedu/address/model/person/DoctorsMatch.java
  src/main/java/seedu/address/ui/DoctorBrowserPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DoctorBrowserPanel.fxml
  src/main/resources/view/DoctorListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/ui/DoctorBrowserPanelTest.java
  src/test/java/seedu/address/ui/PatientInfoPanelTest.java
Labels: priority.Medium, type.Enhancement

#191 implemented changed appt status display for patient
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddPatientCommand.java
  src/main/java/seedu/address/logic/commands/DeletePatientCommand.java
  src/main/java/seedu/address/logic/commands/EditPatientCommand.java
  src/main/java/seedu/address/logic/commands/ListPatientCommand.java
  src/main/java/seedu/address/logic/commands/MarkAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/SearchAdvancedPatientCommand.java
  src/main/java/seedu/address/logic/commands/SearchPatientApptStatusCommand.java
  src/main/java/seedu/address/logic/commands/SearchPatientCommand.java
  src/main/java/seedu/address/logic/commands/SearchPatientTagCommand.java
  src/main/java/seedu/address/logic/commands/SelectPatientCommand.java
  src/main/java/seedu/address/model/person/Patient.java
  src/main/java/seedu/address/model/person/PersonId.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPatient.java
  src/test/data/JsonSerializableDocXTest/duplicatePatientDocX.json
  src/test/data/JsonSerializableDocXTest/typicalPatientsDocX.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPatientTest.java
Labels: type.Epic

#198 added more test cases and set phone restriction
  src/main/java/seedu/address/logic/commands/EditDoctorCommand.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/tag/Specialisation.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteDoctorCommandTest.java
  src/test/java/seedu/address/logic/commands/EditDoctorCommandTest.java
  src/test/java/seedu/address/logic/commands/EditDoctorDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditDoctorCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SearchDoctorSpecialisationCommandParserTest.java
  src/test/java/seedu/address/testutil/DoctorUtil.java
  src/test/java/seedu/address/testutil/TypicalDoctors.java
  src/test/java/systemtests/AddDoctorCommandSystemTest.java
  src/test/java/systemtests/DocXSystemTest.java
Labels: priority.High

#205 added more doctor test cases + updated UG
  docs/UserGuide.adoc
  docs/team/ongsiying.adoc
  src/main/java/seedu/address/logic/commands/AddDoctorCommand.java
  src/main/java/seedu/address/logic/commands/DeleteDoctorCommand.java
  src/main/java/seedu/address/logic/commands/DoctorMatchCommand.java
  src/main/java/seedu/address/logic/commands/EditDoctorCommand.java
  src/main/java/seedu/address/logic/commands/ListDoctorCommand.java
  src/main/java/seedu/address/logic/commands/SelectDoctorCommand.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DoctorMatchCommandTest.java
  src/test/java/seedu/address/logic/parser/AddDoctorCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DoctorMatchCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ListDoctorCommandParserTest.java
Labels: priority.High
